name: Lint

on: ["pull_request"]

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9.19
          architecture: x64
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install mypy
        run: pip install mypy
      - name: Install Poetry and package
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry install
      - name: Run mypy
        run: poetry run mypy .
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable